version: "3.9"

services:

  mysql:
      image: mysql:8.0
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: uqar
        
  go-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - mysql

volumes:
  todo-mysql-data:
    external: true
    name: todo-mysql-data
   
