# SERVICE part
apiVersion: v1
kind: Service
metadata:
  name: webservice
  # Give link to Service
  labels:
    app: webservice
spec:
  ports:
    - port: 8080
  selector:
    # LINK Service-deployment and Service-pod
    app: webservice
  type: NodePort
---
# DEPLOYMENT part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  # replicas: 1
  selector:
    # LINK Deployment-Pod
    matchLabels:
      app: webservice

  # POD part
  template:
    metadata:
      # Give link to Pod
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: docker.io/frednh1993/uqar_systemes_distribues:webservice
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: User
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
