apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  ports:
    - port: 80
  selector:
    app: webservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: docker.io/library/bdandgo-rest_api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
