version: "3.9"
services:
  rest_api:
    build: 
      context: .
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: uqar
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    # environment:
    #   MYSQL_ROOT_PASSWORD: pass
    #   MYSQL_DATABASE: uqar

volumes:
  mysql-data: