apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  ports:
    - port: 8080
  selector:
    app: webservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: docker.io/library/site-web-uqar:latest 
        imagePullPolicy: Never
        env:
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysql-db-secret 
              key: password
        - name : DB_USER
          value: root
        ports:
        - containerPort: 8080